[programs.devnet]
myepicproject = "AD8mVbetMZWkhJpsfzynKFxsFYaah18a3kidcoNwn6CR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kaleblape/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
